"""
This file contain 2 Dictionary: [State_Element_No_Outline] and [State_Element_Outline]
It is used as a correspond of each state to a HTML Element in Sporcle to allow Browser to click on
"""
class State_Element:
	State_Element_No_Outline = {
		"Louisiana":'a19',
		"Arkansas":'a23',
		"Florida":'a25',
		"New York":'a43',
		"Georgia": 'a30',
		"Kansas": 'a16',
		"Ohio": 'a29',
		"Connecticut": 'a44',
		"Iowa": 'a21',
		"Utah": 'a5',
		"Illinois": 'a28',
		"New Mexico": 'a9',
		"New Jersey": 'a42',
		"Texas": 'a18',
		"Pennsylvania": 'a39',
		"Hawaii": 'a12',
		"Oregon": 'a1',
		"Nevada": 'a4',
		"Tennessee": 'a31',
		"Alaska": 'a11',
		"Virginia": 'a37',
		"Colorado": 'a8',
		"Kentucky": 'a34',
		"South Carolina": 'a35',
		"Wisconsin": 'a27',
		"Washington": 'a0',
		"Michigan": 'a32',
		"Nebraska": 'a15',
		"Montana": 'a7',
		"Indiana": 'a33',
		"West Virginia": 'a38',
		"Arizona": 'a6',
		"Idaho": 'a2',
		"Rhode Island": 'a45',
		"Alabama": 'a24',
		"Missouri": 'a22',
		"California": 'a3',
		"Minnesota": 'a20',
		"Vermont": 'a48',
		"Oklahoma": 'a17',
		"Wyoming": 'a10',
		"New Hampshire": 'a47',
		"Massachusetts": 'a46',
		"Delaware": 'a41',
		"Maine": 'a49',
		"Mississippi": 'a26',
		"South Dakota": 'a14',
		"North Dakota": 'a13',
		"Maryland": 'a40',
		"North Carolina": 'a36'
	}

	State_Element_Outline = {
		"Louisiana":'a17',
		"Arkansas":'a3',
		"Florida":'a8',
		"New York":'a31',
		"Georgia": 'a9',
		"Kansas": 'a15',
		"Ohio": 'a34',
		"Connecticut": 'a6',
		"Iowa": 'a14',
		"Utah": 'a43',
		"Illinois": 'a12',
		"New Mexico": 'a30',
		"New Jersey": 'a29',
		"Texas": 'a42',
		"Pennsylvania": 'a37',
		"Hawaii": 'a10',
		"Oregon": 'a36',
		"Nevada": 'a27',
		"Tennessee": 'a41',
		"Alaska": 'a1',
		"Virginia": 'a45',
		"Colorado": 'a5',
		"Kentucky": 'a16',
		"South Carolina": 'a39',
		"Wisconsin": 'a48',
		"Washington": 'a46',
		"Michigan": 'a21',
		"Nebraska": 'a26',
		"Arkansas": 'a3',
		"Montana": 'a25',
		"Indiana": 'a13',
		"West Virginia": 'a47',
		"Arizona": 'a2',
		"North Carolina": 'a32',
		"Idaho": 'a11',
		"Rhode Island": 'a38',
		"Alabama": 'a0',
		"Missouri": 'a24',
		"California": 'a4',
		"Minnesota": 'a22',
		"Vermont": 'a44',
		"Oklahoma": 'a35',
		"Wyoming": 'a49',
		"New Hampshire": 'a28',
		"Massachusetts": 'a20',
		"Delaware": 'a7',
		"Maine": 'a18',
		"Mississippi": 'a23',
		"South Dakota": 'a40',
		"North Dakota": 'a33',
		"Maryland": 'a19'
	}

	State_Element_Hidden = {
		"Louisiana":'a7',
		"Arkansas":'a1',
		"Florida":'a3',
		"New York":'a21',
		"Georgia": 'a28',
		"Kansas": 'a34',
		"Ohio": 'a12',
		"Connecticut": 'a30',
		"Iowa": 'a6',
		"Utah": 'a44',
		"Illinois": 'a4',
		"New Mexico": 'a39',
		"New Jersey": 'a23',
		"Texas": 'a13',
		"Pennsylvania": 'a19',
		"Hawaii": None,
		"Oregon": 'a42',
		"Nevada": 'a38',
		"Tennessee": 'a17',
		"Alaska": None,
		"Virginia": 'a15',
		"Colorado": 'a32',
		"Kentucky": 'a27',
		"South Carolina": 'a18',
		"Wisconsin": 'a14',
		"Washington": 'a45',
		"Michigan": 'a11',
		"Nebraska": 'a37',
		"Montana": 'a36',
		"Indiana": 'a5',
		"West Virginia": 'a46',
		"Arizona": 'a31',
		"Idaho": 'a33',
		"Rhode Island": 'a20',
		"Alabama": 'a0',
		"Missouri": 'a10',
		"California": 'a2',
		"Minnesota": 'a35',
		"Vermont": 'a16',
		"Oklahoma": 'a41',
		"Wyoming": 'a47',
		"New Hampshire": 'a24',
		"Massachusetts": 'a25',
		"Delaware": 'a29',
		"Maine": 'a8',
		"Mississippi": 'a9',
		"South Dakota": 'a43',
		"North Dakota": 'a40',
		"Maryland": 'a26',
		"North Carolina": 'a22'
	}

